[package]
name = 'walrus-profile'

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }


[addresses]
walrus_profile = "0x0"
sui = "0x2"
polymedia_profile = "0x0"